### ISSUE TITLE
Premier Tennis

### ISSUE THREAD

**Issue by nickevansuk** [openactive/implementation-tracker#233]
## Development Progress Tracker

This issue aims to provide public visibility of this new OpenActive integration's development progress. The task list below tracks high level progress at-a-glance, while comments on this issue are used to provide updates in more detail.

### Speculative
- [x] OpenActive community engagement
- [x] Scoping
- [x] Scheduling

### In Development
- [x] Dataset site built
- [x] Open data feeds built
- [x] Open Booking API built
- [x] OpenActive Conformance Certificate generated (via OpenActive Test Suite)
- [x] Dataset site updated

### In Review
- [x] OpenActive community feedback
- [x] Deployed to production (https://api.premiertennis.co.uk/openactive)
- [x] First integration live

### Certified and Live
- [ ] Added to OpenActive Data Catalog

**Comment by drinkynet** [comment]
@nickevansuk [new data site](https://api.premiertennis.co.uk/openactive) is live. Will drop the PR in tomorrow morning.

**Comment by nickevansuk** [comment]
Great news @drinkynet - just noting that the "Registration" and "Terms of Service" links currently return a variation of:

```
// 20230220174950
// https://api.premiertennis.co.uk/docs/registration

{
  "statusCode": 405,
  "error": {
    "type": "NOT_ALLOWED",
    "description": "Method not allowed. Must be one of: OPTIONS"
  }
}
```

And the "Discussion" URL is currently empty

**Comment by drinkynet** [comment]
`discussionUrl` is fixed, currently inventing the registration page :)

**Comment by drinkynet** [comment]
Registration link is fixed now too.

**Comment by drinkynet** [comment]
@nickevansuk Re the certificate; is there some sort of timer on it? There have been no changes to the OA feeds or OB API since the certificate was generated, an unintended code freeze if you will :)

**Comment by nickevansuk** [comment]
No timer on it, but the test suite is updated from time-to-time. Sometimes there're bugs identified or tests added to make the testing more robust. The fingerprint of the cert must match the fingerprint of the test suite in the master branch for it to be valid: hence the recommendation to have the test suite running as part of CI. As all implementations of OB are production systems with their own roadmaps and dev cycles, and many are cloud-based solutions with regular release cycles, a cert that says "this once was compliant many moons ago" is of limited value :)

Ideally the test suite cert is outputted directly to cloud storage and hosted on a relevant domain. One idea was to make this native to the test suite itself, so that it could optionally output to Azure or Amazon S3 if it was given the right keys - though the other side of the argument is that's it's just a few lines in a CI script so doesn't add much value. Do you think you'd find that helpful?

**Comment by nickevansuk** [comment]
(See [here](https://github.com/openactive/OpenActive.Server.NET/blob/b66ba4172f4d839866729808ada30d8b9bafce54/.github/workflows/openactive-test-suite.yml#L105-L112) for an example for Azure in GitHub CI)

**Comment by drinkynet** [comment]
_Is_ compliant with version xyz of the spec, is a little different to 'was compliant many moons ago',  but I get your point. 

The constant daily/weekly dev cycle pattern isn't in play here. And since CI runs when a change happens, the cert can expire before the next change happens if the changes are infrequent enough and the test suite updates enough.

I'll schedule a re-run of the tests on the latest suite. Not implementing the test data creation hooks is going to bite me here isn't it :)

**Comment by nickevansuk** [comment]
Interesting - I wouldn't have thought the test suite would update frequently enough for that to be the case, let's see.

Haha - hopefully not! I know Playfinder/Bookteq do a database restore before each CI run so that could be something to consider

**Comment by nickevansuk** [comment]
Also super minor but the "Discussion" link should go to:
- https://github.com/Courtside-Hubs/OADatasetSite/issues

Rather than:
- https://github.com/Courtside-Hubs/OADatasetSite

**Comment by drinkynet** [comment]
Cool on the Discussion URL, which links should be relative?

**Comment by nickevansuk** [comment]
Sorry typo, see above. Should be absolute rather than relative!

**Comment by drinkynet** [comment]
fixed

**Comment by drinkynet** [comment]
I thought I'd fixed the issues link, will go and see what's up

**Comment by nickevansuk** [comment]
Looks great!

Remaining issues appear to be:
1. Some gaps in the data https://github.com/openactive/data-catalogs/pull/31#issuecomment-1480064577
2. Certificate needs regenerating

**Comment by nickevansuk** [comment]
Can confirm (2) above is now complete, with a new certificate generated: https://api.premiertennis.co.uk/openactive/certificate
